name: "publish"

on:
  push:
    branches:
      - 'release/*'

# This is the example from the readme.
# On each push to the `release` branch it will create or update a GitHub release, build your app, and upload the artifacts to the release.

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest" # for Arm based macs (M1 and above).
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest" # for Intel based macs.
            args: "--target x86_64-apple-darwin"
          # - platform: "ubuntu-22.04" # for Tauri v1 you could replace this with ubuntu-20.04.
          #   args: ""
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      # - name: install dependencies (ubuntu only)
        # if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        # run: |
        #   sudo apt-get update
        #   sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
        # webkitgtk 4.0 is for Tauri v1 - webkitgtk 4.1 is for Tauri v2.
        # You can remove the one that doesn't apply to your app to speed up the workflow a bit.

      - name: install frontend dependencies
        run: yarn install # change this to npm, pnpm or bun depending on which one you use.

      # 使用 rust-cache Action 可以缓存 Cargo 的注册表和构建工件，大幅减少后续构建的时间
      - name: Cache Rust build artifacts
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      # - uses: tauri-apps/tauri-action@v0
      - uses: baipgydx729/tauri-action-cn@V1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }} 
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }} 
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          #将 releaseDraft 设置为 true，这样会自动创建 Release 草稿而不是直接发布，给你一个检查确认的机会
          releaseDraft: false
          prerelease: false
          includeUpdaterJson: true
          updaterJsonPreferNsis: true
          args: ${{ matrix.args }}

      # - name: Upload release artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: release-${{ matrix.platform }}
      #     path: src-tauri/target/release/bundle/**

      # - name: Upload release TO Server
      #   uses: wlixcc/SFTP-Deploy-Action@v1.2.6
      #   with:
      #     username: 'root'
      #     server: '${{ secrets.SSH_SERVER_IP }}'
      #     ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     local_path: './src-tauri/target/*'
      #     remote_path: '/www/wwwroot/www.smiwork.com/package/latest'
      #     rsyncArgs: '--exclude=*.map'
      #     sftpArgs: '-o ConnectTimeout=5'